ifdef CONFIG_HTC_DEBUG
obj-y += htc_debug_tools.o

obj-$(CONFIG_HTC_PROCESS_DEBUG) += htc_process_debug.o

# bootmsg
obj-$(CONFIG_HTC_DEBUG_SAVE_BOOT_MSG) += bootmsg.o

# kallsyms-export
obj-$(CONFIG_KALLSYMS) += kallsyms-export.o

obj-$(CONFIG_DIRTY_SYSTEM_DETECTOR) += dirty_file_detector.o
obj-$(CONFIG_HTC_DEBUG_HBRAMLOG) += hb_ramlog.o
endif
